# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='presentation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
