# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
