# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_paper_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='google_email',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='personal_email',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
