# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_paper_presentation_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='link',
        ),
        migrations.AlterField(
            model_name='paper',
            name='gdrive_id',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='gdrive_link',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='presentation_place',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
