# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0007_auto_20161115_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='presentation_date',
            field=models.TextField(null=True),
        ),
    ]
