# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0008_auto_20161116_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='gdrive_content',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
